FROM node:20-alpine

#install playwright
RUN npx playwright install --with-deps

WORKDIR /usr/src/app

COPY package.json .
COPY . .

RUN npm install -g yarn

RUN yarn  

EXPOSE 3000

CMD ["yarn", "start"] 