FROM node:20-alpine

# Install Playwright dependencies using apk
RUN apk update && \
    apk add --no-cache libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxcomposite1 libxrandr2 libxdamage1 libxkbcommon0 libx11-xcb1 libxcb-dri3-0 libxss1 libxtst6 libgtk-3-0

WORKDIR /usr/src/app

COPY package.json .
COPY . .

RUN npm install -g yarn

RUN yarn  

EXPOSE 3000

CMD ["yarn", "start"] 